# Generated by Django 2.2 on 2019-04-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_button', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buttonresponse',
            name='status_code',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buttonresponse',
            name='response_date',
            field=models.DateTimeField(),
        ),
    ]
